- Build a linear models of degree 2 to estimate $v_l$ <br>
- Use 4 samples of train data for training and  <br>
- Use gradient descent method for finding the weights. <br>
- Update the weights for each sample. <br>
- Do weight updates for 100 epochs. (use train data only) <br>
- Report the values predicted on the 3 samples of test data in the variable Y_pred_test (shape is (3,))

- Hint : Take inputs in units of metres (0.6, 0.5, 0.3, 0.2)


### Train Data
| Sonar S | $v_l$   |$v_r$|
|---------|---------|-----|
|60cm |10cm/sec |10cm/sec |
| 50cm |9cm/sec| 9cm/sec |
| 30cm | 7cm/sec | 4cm/sec |
|20cm | 4cm/sec | 0cm/sec|

### Test Data
| Sonar S | $v_l$   |$v_r$|
|---------|---------|-----|
|40cm |8cm/sec |8cm/sec |
| 35cm |7.5cm/sec| 6cm/sec |
| 25cm | 6cm/sec | 2cm/sec |

# **Training**

In [0]:
import numpy as np

In [0]:
S=[0.6,0.5,0.3,0.2]
vLd=[10,9,7,4]
S=np.array(S)
vLd=np.array(vLd)

In [0]:
def create_A(x,D):
  A=[]
  for i in x:
    temp=[]
    for d in range(0,D+1):
      temp+=[i**d]
    A+=[temp]
  return np.array(A)

In [0]:
X_train=S
Yd=vLd
D=2

In [0]:
def initialize_w(D):
  return np.random.random(D+1)

In [0]:
def train_model(x,yd,D,eta):
  w=initialize_w(D)
  print("x =",x," ",x.shape)
  print(" ")
  print("yd =",yd," ",yd.shape)
  print(" ")
  print("w0 =",w," ",w.shape)
  A=create_A(x,D)
  print(" ")
  print("A =",A," ",A.shape)
  print(" ")
  E=np.zeros((x.shape[0],1))
  ctr=0
  for i in range(0,100):
    ctr+=1
    for j in range(0,x.shape[0]):
      a=A[j].reshape(D+1,1)
      w=w.reshape(D+1,1)
      y=a.T.dot(w)
      y=y[0][0]
      e=yd[j]-y
      e=np.array(e)
      E[j]=e**2
      e=e.reshape(1,1)
      w = w + eta*(a.dot(e))
  print("Counter =",ctr)
  return w,E

In [7]:
w,E=train_model(S,vLd,D,0.06)
print("Final w =",w," ",w.shape)
print(" ")
print("Final error after 100 epochs E =",E," ",E.shape)

x = [0.6 0.5 0.3 0.2]   (4,)
 
yd = [10  9  7  4]   (4,)
 
w0 = [0.96917053 0.73186253 0.72227448]   (3,)
 
A = [[1.   0.6  0.36]
 [1.   0.5  0.25]
 [1.   0.3  0.09]
 [1.   0.2  0.04]]   (4, 3)
 
Counter = 100
Final w = [[4.16142992]
 [6.2489602 ]
 [4.51516845]]   (3, 1)
 
Final error after 100 epochs E = [[0.22189325]
 [0.3017298 ]
 [0.23120868]
 [2.88301169]]   (4, 1)


# **Testing**

In [0]:
vLd2=np.array([8,7.5,6])
S2=np.array([0.4,0.35,0.25])

In [0]:
A2=create_A(S2,D)

In [10]:
Y_pred_test=A2.dot(w)
print(vLd2)
print(Y_pred_test.reshape(D+1,))

[8.  7.5 6. ]
[7.38344096 6.90167413 6.005868  ]
