# Quiz

## Question 1
I have a function $y=\log x + x, x\in(1,2)$. I measured it at 3 points $x\in\{1, 1.5, 1.7\}$. Now, I thought I can fit a model $\hat{y} = w_0 + w_3 x^3$ to this data, so that I could approximate $y$ for any value of $x$. 

a. Find the optimal values of weights $w_0, w_3$ that minimize the squared error. 

b. If I test my model at $x=1.3$, what will be the squared error $E=(y-\hat{y})^2$?

You can use pen-paper to find the answers. Write your final answers below in the variables with names w_0, w_3 and E

In [1]:
# YOUR CODE HERE
import numpy as np
x=[1,1.5,1.7]
yd=np.log(x)+x
print(yd)
A=[]
for i in x:
  A+=[[1 ,i*i*i]]
A=np.array(A)
print(A)
w=np.linalg.inv(A.T.dot(A)).dot(A.T)
w=w.dot(yd)
print(w)

[1.         1.90546511 2.23062825]
[[1.    1.   ]
 [1.    3.375]
 [1.    4.913]]
[0.72072894 0.32018804]


In [2]:
w_0=w[0]
w_3=w[1]
print(w_0,w_3)

0.7207289368130763 0.32018804357570096


In [3]:
y=A.dot(w)
print(y)

[1.04091698 1.80136358 2.29381279]


In [4]:
x=1.3
yd=np.log(x)+x
print(yd)
A=[]
i=x
A+=[[1 ,i*i*i]]
A=np.array(A)
print(A)
y=A.dot(w)
print(y)
E=(y-yd)**2
E=E[0]
print(E)

1.562364264467491
[[1.    2.197]]
[1.42418207]
0.01909431926888624


In [5]:
print(w_0,w_3,E)

0.7207289368130763 0.32018804357570096 0.01909431926888624


# Python Basics

### Sum of squares
Given  a list of floats, find  the sum of squares <br>
Eg., 
l = [1, 2, 3] <br>
sum_sqs(l) == 14

In [0]:
def sum_sqs(l):
  """
  Input:
    l : list of ints
    y : int, sum of squares of elements of l
  """
  # YOUR CODE HERE
  sum=0
  for i in l:
    sum+=i**2
  return sum

In [7]:
sum_sqs([3.0,4.0])

25.0

### Sub Matrix
Given a matrix X (numpy array) of shape (m, n) where m>=3, n>=3. Find the first sub-matrix Y of size (3, 3)
Eg.,
$$
\begin{align}
M = \begin{bmatrix}
[11, & 12, & 13, &14], \\
[21, & 22, & 22, & 23],\\
[31, & 32, & 33, & 34],\\
[41, & 42, & 43, & 44],\\
\end{bmatrix}
\end{align}
$$
$$
\begin{align}
Y = \begin{bmatrix}
[11, & 12, & 13,], \\
[21, & 22, & 22,],\\
[31, & 32, & 33,],\\
\end{bmatrix}
\end{align}
$$

In [0]:
def first_sub_matrix_3_3(X):
  """
  Input:
    X : numpy array of shape (m, n), m>=3, n>=3
  Output:
    Y : numpy array of shape (3, 3); first submatrix of X
  """
  # YOUR CODE HERE
  Y=[]
  m=X.shape[0]
  n=X.shape[1]
  if(m>=3 and n>=3):
    for i in range(0,3):
      temp=[]
      for j in range(0,3):
        temp+=[X[i][j]]
      Y+=[temp]
  return np.array(Y)

In [9]:
X=[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
X=np.array(X)
first_sub_matrix_3_3(X)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Windows
Given a list l, and window size m, split it into windows of size m as shown below. <br>
Eg., l = [1, 2, 3, 4, 5, 6], m = 3 <br>
get_windows(l, m) --> [ [1, 2, 3], [2, 3, 4],  [3, 4, 5], [4, 5, 6]]

In [0]:
def get_windows(l, m):
  """
    Input:
      l : list of ints
      m : int, window_length
    Output:
      y : list of lists, each inner list is a window
  """
  # YOUR CODE HERE
  y=[]
  for i in range(0,len(l)):
    temp=[]
    for j in range(i,m+i):
      try:
        temp+=[l[j]]
      except:
        break
    if(len(temp)==m):
      y+=[temp]
      
  return y

In [11]:
get_windows([1, 2, 3, 4, 5, 6,7,8,9],3)

[[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9]]